#!/bin/bash
# Muutujad, väärtuste omistamine ning arvutamine Ülesanne2
aasta="2016"
president="Kersti Kaljulaid"
lause=". aastal valiti Eesti presidendiks "
#
vastus=$aasta$lause$president
#
echo $vastus
